// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"katanaid/database/ent/emailverification"
	"katanaid/database/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// EmailVerification is the model entity for the EmailVerification schema.
type EmailVerification struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TokenHash holds the value of the "token_hash" field.
	TokenHash string `json:"token_hash,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EmailVerificationQuery when eager-loading is set.
	Edges                    EmailVerificationEdges `json:"edges"`
	user_email_verifications *int
	selectValues             sql.SelectValues
}

// EmailVerificationEdges holds the relations/edges for other nodes in the graph.
type EmailVerificationEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EmailVerificationEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EmailVerification) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case emailverification.FieldID:
			values[i] = new(sql.NullInt64)
		case emailverification.FieldTokenHash:
			values[i] = new(sql.NullString)
		case emailverification.FieldExpiresAt, emailverification.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case emailverification.ForeignKeys[0]: // user_email_verifications
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EmailVerification fields.
func (_m *EmailVerification) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case emailverification.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case emailverification.FieldTokenHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_hash", values[i])
			} else if value.Valid {
				_m.TokenHash = value.String
			}
		case emailverification.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case emailverification.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case emailverification.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_email_verifications", value)
			} else if value.Valid {
				_m.user_email_verifications = new(int)
				*_m.user_email_verifications = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EmailVerification.
// This includes values selected through modifiers, order, etc.
func (_m *EmailVerification) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the EmailVerification entity.
func (_m *EmailVerification) QueryUser() *UserQuery {
	return NewEmailVerificationClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this EmailVerification.
// Note that you need to call EmailVerification.Unwrap() before calling this method if this EmailVerification
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EmailVerification) Update() *EmailVerificationUpdateOne {
	return NewEmailVerificationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EmailVerification entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EmailVerification) Unwrap() *EmailVerification {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EmailVerification is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EmailVerification) String() string {
	var builder strings.Builder
	builder.WriteString("EmailVerification(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("token_hash=")
	builder.WriteString(_m.TokenHash)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// EmailVerifications is a parsable slice of EmailVerification.
type EmailVerifications []*EmailVerification
