// Code generated by ent, DO NOT EDIT.

package ent

import (
	"katanaid/database/ent/contact"
	"katanaid/database/ent/emailverification"
	"katanaid/database/ent/schema"
	"katanaid/database/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	contactFields := schema.Contact{}.Fields()
	_ = contactFields
	// contactDescCreatedAt is the schema descriptor for created_at field.
	contactDescCreatedAt := contactFields[2].Descriptor()
	// contact.DefaultCreatedAt holds the default value on creation for the created_at field.
	contact.DefaultCreatedAt = contactDescCreatedAt.Default.(func() time.Time)
	emailverificationFields := schema.EmailVerification{}.Fields()
	_ = emailverificationFields
	// emailverificationDescCreatedAt is the schema descriptor for created_at field.
	emailverificationDescCreatedAt := emailverificationFields[2].Descriptor()
	// emailverification.DefaultCreatedAt holds the default value on creation for the created_at field.
	emailverification.DefaultCreatedAt = emailverificationDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmailVerified is the schema descriptor for email_verified field.
	userDescEmailVerified := userFields[4].Descriptor()
	// user.DefaultEmailVerified holds the default value on creation for the email_verified field.
	user.DefaultEmailVerified = userDescEmailVerified.Default.(bool)
}
